### ISSUE TITLE
Illegal annotations on long and sql.date which were used in entities.

### ISSUE THREAD

**Issue by tczhaodachuan** [typischmann/retail-crm#33]
Caused by: com.sun.xml.bind.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
java.sql.Timestamp does not have a no-arg default constructor.
    this problem is related to the following location:
        at java.sql.Timestamp
        at public java.sql.Timestamp org.crm.entities.Employee.getDelta_ts()
        at org.crm.entities.Employee
java.sql.Date does not have a no-arg default constructor.
    this problem is related to the following location:
        at java.sql.Date
        at public java.sql.Date org.crm.entities.Employee.getEndDate()
        at org.crm.entities.Employee

**Comment by typischmann** [comment]
I guess that you have solved this problem. if so, don't forget to close this issue \(0_0)/

**Comment by tczhaodachuan** [comment]
The orders issue has resolved, but the employee entity has not. It needs DTO to resolve this.

**Comment by typischmann** [comment]
What does this issue have to do with DTO ? I think DTO should be another theme which is now only belonging to web service module. 

In my experience, this problem is usually caused by the lacking of constructor for java.sql.Date and Timestamp. But now, I have seen you added the SqlDateAdapter . Then, this problem should be resolved in service module. Isn't it?

**Comment by tczhaodachuan** [comment]
Has been fixed once introduced the adapter classes.
